/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p.i.fame;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.OsDAO;
import model.OrdemServico;
import model.Venda;
import model.VendaDAO;

/**
 *
 * @author User
 */
public class TelaOS extends javax.swing.JFrame {

    /**
     * Creates new form TelaVendas
     */
    public TelaOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnsPanel = new javax.swing.JPanel();
        CadastroBtn = new javax.swing.JButton();
        EditarBtn = new javax.swing.JButton();
        ExcluirBtn = new javax.swing.JButton();
        VoltarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        vendasButton = new javax.swing.JButton();
        OSButton = new javax.swing.JButton();
        detalhesPanel = new javax.swing.JPanel();
        NomeLabel = new javax.swing.JLabel();
        DataReceLabel = new javax.swing.JLabel();
        TelefoneLabel = new javax.swing.JLabel();
        FormaPagLabel = new javax.swing.JLabel();
        PrecoLabel = new javax.swing.JLabel();
        ServicoLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        servicoTextArea = new javax.swing.JTextArea();
        nomeLabel = new javax.swing.JLabel();
        telefoneLabel = new javax.swing.JLabel();
        dataRecLabel = new javax.swing.JLabel();
        precoLabel = new javax.swing.JLabel();
        formaPagLabel = new javax.swing.JLabel();
        NosLabel = new javax.swing.JLabel();
        numeroOSLabel = new javax.swing.JLabel();
        StatusLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        jaPagoLabel = new javax.swing.JLabel();
        JaPagoLabel = new javax.swing.JLabel();
        filtroComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        BtnsPanel.setBackground(new Color(255,255,0,96));

        CadastroBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        CadastroBtn.setText("<html><center>Registrar<br>O.S</center></html>");
        CadastroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroBtnActionPerformed(evt);
            }
        });

        EditarBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        EditarBtn.setText("<html><center>Fechar<br>O.S</center></html>");
        EditarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarBtnActionPerformed(evt);
            }
        });

        ExcluirBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        ExcluirBtn.setText("<html><center>Excluir<br>O.S</center></html>");
        ExcluirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BtnsPanelLayout = new javax.swing.GroupLayout(BtnsPanel);
        BtnsPanel.setLayout(BtnsPanelLayout);
        BtnsPanelLayout.setHorizontalGroup(
            BtnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnsPanelLayout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(CadastroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(EditarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(ExcluirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        BtnsPanelLayout.setVerticalGroup(
            BtnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnsPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(BtnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExcluirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        VoltarBtn.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        VoltarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        VoltarBtn.setBorder(null);
        VoltarBtn.setContentAreaFilled(false);
        VoltarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VoltarBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        VoltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarBtnActionPerformed(evt);
            }
        });

        Tabela.setBackground(new java.awt.Color(255, 255, 255));
        Tabela.setFont(new java.awt.Font("Aldrich", 0, 14)); // NOI18N
        Tabela.setForeground(new java.awt.Color(0, 0, 0));
        Tabela.setModel(montarTabela());
        Tabela.setGridColor(new java.awt.Color(0, 0, 255));
        Tabela.setSelectionBackground(new Color(255, 255, 0, 63));
        Tabela.setSelectionForeground(new java.awt.Color(0, 0, 0));
        Tabela.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Tabela.setShowGrid(true);
        Tabela.getTableHeader().setReorderingAllowed(false);
        Tabela.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TabelaFocusLost(evt);
            }
        });
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela);

        jPanel2.setBackground(new java.awt.Color(37, 86, 255));

        homeButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setText("⌂");
        homeButton.setBorderPainted(false);
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        vendasButton.setBackground(new java.awt.Color(255, 255, 255));
        vendasButton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        vendasButton.setForeground(new java.awt.Color(0, 0, 0));
        vendasButton.setText("VENDAS");
        vendasButton.setBorder(null);
        vendasButton.setBorderPainted(false);
        vendasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendasButtonActionPerformed(evt);
            }
        });

        OSButton.setBackground(new java.awt.Color(0, 0, 0));
        OSButton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        OSButton.setForeground(new java.awt.Color(255, 255, 255));
        OSButton.setBorder(null);
        OSButton.setLabel("<html><center>ORDEM<br>SERVIÇO</center></html>");
        OSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OSButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vendasButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(OSButton, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButton)
                .addGap(178, 178, 178)
                .addComponent(vendasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {OSButton, vendasButton});

        detalhesPanel.setBackground(new java.awt.Color(37, 86, 255));

        NomeLabel.setFont(new java.awt.Font("Aldrich", 0, 18)); // NOI18N
        NomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        NomeLabel.setText("Nome:");

        DataReceLabel.setFont(new java.awt.Font("Aldrich", 0, 18)); // NOI18N
        DataReceLabel.setForeground(new java.awt.Color(255, 255, 255));
        DataReceLabel.setText("Data Recepção:");

        TelefoneLabel.setFont(new java.awt.Font("Aldrich", 0, 18)); // NOI18N
        TelefoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        TelefoneLabel.setText("Telefone:");

        FormaPagLabel.setFont(new java.awt.Font("Aldrich", 0, 18)); // NOI18N
        FormaPagLabel.setForeground(new java.awt.Color(255, 255, 255));
        FormaPagLabel.setText("Forma Pagamento:");

        PrecoLabel.setFont(new java.awt.Font("Aldrich", 0, 18)); // NOI18N
        PrecoLabel.setForeground(new java.awt.Color(255, 255, 255));
        PrecoLabel.setText("Preço:");

        ServicoLabel.setFont(new java.awt.Font("Aldrich", 0, 18)); // NOI18N
        ServicoLabel.setForeground(new java.awt.Color(255, 255, 255));
        ServicoLabel.setText("Serviço:");

        servicoTextArea.setEditable(false);
        servicoTextArea.setBackground(new java.awt.Color(255, 255, 255));
        servicoTextArea.setColumns(20);
        servicoTextArea.setFont(new java.awt.Font("Aldrich", 0, 15)); // NOI18N
        servicoTextArea.setForeground(new java.awt.Color(0, 0, 0));
        servicoTextArea.setLineWrap(true);
        servicoTextArea.setRows(5);
        servicoTextArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        servicoTextArea.setFocusable(false);
        servicoTextArea.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane2.setViewportView(servicoTextArea);

        nomeLabel.setFont(new java.awt.Font("Aldrich", 0, 14)); // NOI18N
        nomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        nomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nomeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        telefoneLabel.setFont(new java.awt.Font("Aldrich", 0, 14)); // NOI18N
        telefoneLabel.setForeground(new java.awt.Color(255, 255, 255));

        dataRecLabel.setFont(new java.awt.Font("Aldrich", 0, 14)); // NOI18N
        dataRecLabel.setForeground(new java.awt.Color(255, 255, 255));

        precoLabel.setFont(new java.awt.Font("Aldrich", 0, 14)); // NOI18N
        precoLabel.setForeground(new java.awt.Color(255, 255, 255));

        formaPagLabel.setFont(new java.awt.Font("Aldrich", 0, 14)); // NOI18N
        formaPagLabel.setForeground(new java.awt.Color(255, 255, 255));

        NosLabel.setFont(new java.awt.Font("Aldrich", 0, 14)); // NOI18N
        NosLabel.setForeground(new java.awt.Color(255, 255, 255));
        NosLabel.setText("Nº O.S:");

        numeroOSLabel.setFont(new java.awt.Font("Aldrich", 0, 12)); // NOI18N
        numeroOSLabel.setForeground(new java.awt.Color(255, 255, 255));

        StatusLabel.setFont(new java.awt.Font("Aldrich", 0, 18)); // NOI18N
        StatusLabel.setForeground(new java.awt.Color(255, 255, 255));
        StatusLabel.setText("Status:");

        statusLabel.setFont(new java.awt.Font("Aldrich", 0, 14)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(255, 255, 255));

        jaPagoLabel.setFont(new java.awt.Font("Aldrich", 0, 14)); // NOI18N
        jaPagoLabel.setForeground(new java.awt.Color(255, 255, 255));

        JaPagoLabel.setFont(new java.awt.Font("Aldrich", 0, 18)); // NOI18N
        JaPagoLabel.setForeground(new java.awt.Color(255, 255, 255));
        JaPagoLabel.setText("Já pago?:");

        detalhesPanel.setVisible(false);

        javax.swing.GroupLayout detalhesPanelLayout = new javax.swing.GroupLayout(detalhesPanel);
        detalhesPanel.setLayout(detalhesPanelLayout);
        detalhesPanelLayout.setHorizontalGroup(
            detalhesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detalhesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detalhesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detalhesPanelLayout.createSequentialGroup()
                        .addComponent(TelefoneLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(detalhesPanelLayout.createSequentialGroup()
                        .addComponent(DataReceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataRecLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(detalhesPanelLayout.createSequentialGroup()
                        .addComponent(PrecoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(precoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(detalhesPanelLayout.createSequentialGroup()
                        .addComponent(FormaPagLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formaPagLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addGroup(detalhesPanelLayout.createSequentialGroup()
                        .addComponent(NomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NosLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numeroOSLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(detalhesPanelLayout.createSequentialGroup()
                        .addComponent(StatusLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(detalhesPanelLayout.createSequentialGroup()
                        .addGroup(detalhesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(detalhesPanelLayout.createSequentialGroup()
                                .addComponent(ServicoLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(detalhesPanelLayout.createSequentialGroup()
                                .addComponent(JaPagoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jaPagoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        detalhesPanelLayout.setVerticalGroup(
            detalhesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detalhesPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(detalhesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(detalhesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numeroOSLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detalhesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TelefoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(telefoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detalhesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DataReceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dataRecLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detalhesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JaPagoLabel)
                    .addComponent(jaPagoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detalhesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(precoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PrecoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detalhesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FormaPagLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formaPagLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detalhesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StatusLabel)
                    .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(ServicoLabel)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        filtroComboBox.setBackground(new java.awt.Color(89, 175, 255));
        filtroComboBox.setFont(new java.awt.Font("Aldrich", 0, 14)); // NOI18N
        filtroComboBox.setForeground(new java.awt.Color(255, 255, 255));
        filtroComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Em serviço", "Entregue" }));
        filtroComboBox.setBorder(null);
        filtroComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Aldrich", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Status:");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(BtnsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(VoltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(filtroComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(detalhesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(VoltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BtnsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filtroComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(detalhesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarBtnActionPerformed
        TelaInicial ti = new TelaInicial();
        ti.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarBtnActionPerformed

    private void ExcluirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirBtnActionPerformed
        int i = getPosicao();
        if (i > -1) {
            int resp = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir essa O.S?");
            if (resp == 0) {
                OsDAO.excluirOS(i);
            }
        }
    }//GEN-LAST:event_ExcluirBtnActionPerformed

    private void CadastroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroBtnActionPerformed
        TelaCadastroOS tco = new TelaCadastroOS();
        tco.setVisible(true);
        dispose();
    }//GEN-LAST:event_CadastroBtnActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        if (filtroComboBox.getSelectedIndex() == 0) {
            Tabela.setModel(montarTabela());
        } else if (filtroComboBox.getSelectedIndex() == 1) {
            Tabela.setModel(montarTabelaEmServico());
        } else if (filtroComboBox.getSelectedIndex() == 2) {
            Tabela.setModel(montarTabelaEntregue());
        }
        detalhesPanel.setVisible(false);
    }//GEN-LAST:event_formWindowGainedFocus

    private void EditarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarBtnActionPerformed
        int id = getPosicao();
        List<OrdemServico> lista = OsDAO.listarOS();

        for (int i = 0; i < lista.size(); i++) {
            OrdemServico os = lista.get(i);

            if (os.getId() == id) {
                if (os.getStatus().equalsIgnoreCase("entregue")) {
                    JOptionPane.showMessageDialog(null, "Essa O.S já foi fechada! Tente outra!");
                } else {
                    TelaFecharOS tfo = new TelaFecharOS(os);
                    tfo.setVisible(true);
                    dispose();
                }
            }
        }
    }//GEN-LAST:event_EditarBtnActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        TelaInicial ti = new TelaInicial();
        ti.setVisible(true);
        dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void vendasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendasButtonActionPerformed
        TelaVendas tv = new TelaVendas();
        tv.setVisible(true);
        dispose();
    }//GEN-LAST:event_vendasButtonActionPerformed

    private void OSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OSButtonActionPerformed
        TelaOS tos = new TelaOS();
        tos.setVisible(true);
        dispose();
    }//GEN-LAST:event_OSButtonActionPerformed

    private void TabelaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TabelaFocusLost

    }//GEN-LAST:event_TabelaFocusLost

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
        int id = getPosicao();
        List<OrdemServico> lista = OsDAO.listarOS();

        for (int i = 0; i < lista.size(); i++) {
            OrdemServico os = lista.get(i);

            if (os.getId() == id) {
                detalhesPanel.setVisible(true);
                numeroOSLabel.setText(String.valueOf(os.getId()));
                nomeLabel.setText(os.getNomeCliente());
                telefoneLabel.setText(os.getTelefone());
                dataRecLabel.setText(os.getDataRecepcao());
                precoLabel.setText("R$" + String.format("%.2f", os.getPreco()));
                formaPagLabel.setText(os.getFormaPagamento());
                servicoTextArea.setText(os.getServico());
                statusLabel.setText(os.getStatus());
                if (os.getStatus().equalsIgnoreCase("Entregue")) {
                    JaPagoLabel.setText("Data Retirada:");
                    jaPagoLabel.setText(os.getDataRetirada());
                } else {
                    JaPagoLabel.setText("Já pago?:");
                    jaPagoLabel.setText(os.getJaPago());
                }
                break;
            }
        }
    }//GEN-LAST:event_TabelaMouseClicked

    private void filtroComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroComboBoxActionPerformed
        // Sem funcionalidade ainda, quando conectar com o BD irá funcionar, chupetinha na manteiga, DALE MENGOOO
        if (filtroComboBox.getSelectedIndex() == 0) {
            Tabela.setModel(montarTabela());
        } else if (filtroComboBox.getSelectedIndex() == 1) {
            Tabela.setModel(montarTabelaEmServico());
        } else if (filtroComboBox.getSelectedIndex() == 2){
            Tabela.setModel(montarTabelaEntregue());
        }

    }//GEN-LAST:event_filtroComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaOS().setVisible(true);
            }
        });
    }

    private DefaultTableModel montarTabela() {
        String[] colunas = {"Nome", "Telefone", "Serviço", "Preço", "Data Recepção", "Status"};

        DefaultTableModel tabela = new DefaultTableModel(colunas, 0);

        ArrayList<OrdemServico> lista = OsDAO.listarOS();

        for (int i = 0; i < lista.size(); i++) {
            OrdemServico os = lista.get(i);

            String[] linhas = {
                os.getNomeCliente(),
                os.getTelefone(),
                os.getServico(),
                String.format("%.2f", os.getPreco()),
                os.getDataRecepcao(),
                os.getStatus()
            };

            tabela.addRow(linhas);
        }
        return tabela;
    }

    private DefaultTableModel montarTabelaEmServico() {
        String[] colunas = {"Nome", "Telefone", "Serviço", "Preço", "Data Recepção", "Já Pago"};

        DefaultTableModel tabela = new DefaultTableModel(colunas, 0);

        ArrayList<OrdemServico> lista = OsDAO.listarOSEmServico();

        for (int i = 0; i < lista.size(); i++) {
            OrdemServico os = lista.get(i);

            String[] linhas = {
                os.getNomeCliente(),
                os.getTelefone(),
                os.getServico(),
                String.format("%.2f", os.getPreco()),
                os.getDataRecepcao(),
                os.getJaPago()
            };

            tabela.addRow(linhas);
        }
        return tabela;
    }

    private DefaultTableModel montarTabelaEntregue() {
        String[] colunas = {"Nome", "Telefone", "Serviço", "Preço", "Data Recepção", "Data Retirada"};

        DefaultTableModel tabela = new DefaultTableModel(colunas, 0);

        ArrayList<OrdemServico> lista = OsDAO.listarOSEntregue();

        for (int i = 0; i < lista.size(); i++) {
            OrdemServico os = lista.get(i);

            String[] linhas = {
                os.getNomeCliente(),
                os.getTelefone(),
                os.getServico(),
                String.format("%.2f", os.getPreco()),
                os.getDataRecepcao(),
                os.getDataRetirada()
            };

            tabela.addRow(linhas);
        }
        return tabela;
    }

    private int getPosicao() {
        int pos = Tabela.getSelectedRow();
        List<OrdemServico> lista;
        if (filtroComboBox.getSelectedIndex() == 0) {
            lista = OsDAO.listarOS();
        } else if (filtroComboBox.getSelectedIndex() == 1) {
            lista = OsDAO.listarOSEmServico();
        } else if (filtroComboBox.getSelectedIndex() == 2) {
            lista = OsDAO.listarOSEntregue();
        } else {
            lista = OsDAO.listarOS();
        }

        if (pos <= -1) {
            JOptionPane.showMessageDialog(null, "Selecione um item para excluir ou atualizar!", "Erro", 2);
        } else {
            OrdemServico os = lista.get(pos);
            return os.getId();
        }
        return pos;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnsPanel;
    private javax.swing.JButton CadastroBtn;
    private javax.swing.JLabel DataReceLabel;
    private javax.swing.JButton EditarBtn;
    private javax.swing.JButton ExcluirBtn;
    private javax.swing.JLabel FormaPagLabel;
    private javax.swing.JLabel JaPagoLabel;
    private javax.swing.JLabel NomeLabel;
    private javax.swing.JLabel NosLabel;
    private javax.swing.JButton OSButton;
    private javax.swing.JLabel PrecoLabel;
    private javax.swing.JLabel ServicoLabel;
    private javax.swing.JLabel StatusLabel;
    private javax.swing.JTable Tabela;
    private javax.swing.JLabel TelefoneLabel;
    private javax.swing.JButton VoltarBtn;
    private javax.swing.JLabel dataRecLabel;
    private javax.swing.JPanel detalhesPanel;
    private javax.swing.JComboBox<String> filtroComboBox;
    private javax.swing.JLabel formaPagLabel;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jaPagoLabel;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JLabel numeroOSLabel;
    private javax.swing.JLabel precoLabel;
    private javax.swing.JTextArea servicoTextArea;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel telefoneLabel;
    private javax.swing.JButton vendasButton;
    // End of variables declaration//GEN-END:variables
}
