package p.i.fame;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import model.OsDAO;
import model.OrdemServico;
import java.awt.*;

/**
 *
 * @author User
 */
public class TelaCadastroOS extends javax.swing.JFrame {

    /**
     * Creates new form TelaVendas
     */
    public TelaCadastroOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formaPagarGp = new javax.swing.ButtonGroup();
        jaPagoGp = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        BtnsPanel = new javax.swing.JPanel();
        CadastroBtn = new javax.swing.JButton();
        EditarBtn = new javax.swing.JButton();
        ExcluirBtn = new javax.swing.JButton();
        VoltarBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        VendasButton = new javax.swing.JButton();
        OSButton = new javax.swing.JButton();
        cadastroPanel = new javax.swing.JPanel();
        nomeTextField = new javax.swing.JTextField();
        nomeLabel = new javax.swing.JLabel();
        telefoneLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        servicoTextArea = new javax.swing.JTextArea();
        descricaoLabel = new javax.swing.JLabel();
        registrarBtn = new javax.swing.JButton();
        precoTextField = new javax.swing.JTextField();
        precoLabel = new javax.swing.JLabel();
        telefoneTextField = new javax.swing.JFormattedTextField();
        simRadioBtn = new javax.swing.JRadioButton();
        jaPagoLabel = new javax.swing.JLabel();
        naoRadioBtn = new javax.swing.JRadioButton();
        formaPagPanel = new javax.swing.JPanel();
        formaPagamentoLabel = new javax.swing.JLabel();
        debitoRadioBtn = new javax.swing.JRadioButton();
        creditoRadioBtn = new javax.swing.JRadioButton();
        dinheiroRadioBtn = new javax.swing.JRadioButton();
        pixRadioBtn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        BtnsPanel.setBackground(new Color(255,255,0,96));

        CadastroBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        CadastroBtn.setText("<html><center>Registrar<br>O.S</center></html>");
        CadastroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroBtnActionPerformed(evt);
            }
        });

        EditarBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        EditarBtn.setText("<html><center>Fechar<br>O.S</center></html>");
        EditarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarBtnActionPerformed(evt);
            }
        });

        ExcluirBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        ExcluirBtn.setText("<html><center>Excluir<br>O.S</center></html>");
        ExcluirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BtnsPanelLayout = new javax.swing.GroupLayout(BtnsPanel);
        BtnsPanel.setLayout(BtnsPanelLayout);
        BtnsPanelLayout.setHorizontalGroup(
            BtnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnsPanelLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(CadastroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(EditarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(ExcluirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        BtnsPanelLayout.setVerticalGroup(
            BtnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnsPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(BtnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExcluirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        VoltarBtn.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        VoltarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        VoltarBtn.setBorder(null);
        VoltarBtn.setContentAreaFilled(false);
        VoltarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VoltarBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        VoltarBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        VoltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarBtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(37, 86, 255));

        homeButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setText("⌂");
        homeButton.setBorderPainted(false);
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        VendasButton.setBackground(new java.awt.Color(255, 255, 255));
        VendasButton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        VendasButton.setForeground(new java.awt.Color(0, 0, 0));
        VendasButton.setText("VENDAS");
        VendasButton.setBorder(null);
        VendasButton.setBorderPainted(false);
        VendasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendasButtonActionPerformed(evt);
            }
        });

        OSButton.setBackground(new java.awt.Color(0, 0, 0));
        OSButton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        OSButton.setForeground(new java.awt.Color(255, 255, 255));
        OSButton.setBorder(null);
        OSButton.setLabel("<html><center>ORDEM<br>SERVIÇO</center></html>");
        OSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OSButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VendasButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(OSButton, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButton)
                .addGap(178, 178, 178)
                .addComponent(VendasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {OSButton, VendasButton});

        cadastroPanel.setBackground(new java.awt.Color(37, 86, 255));

        nomeTextField.setBackground(new Color(255,255,255, 165));
        nomeTextField.setFont(new java.awt.Font("Aldrich", 0, 22)); // NOI18N
        nomeTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        nomeLabel.setFont(new java.awt.Font("Aldrich", 0, 20)); // NOI18N
        nomeLabel.setText("Nome:");

        telefoneLabel.setFont(new java.awt.Font("Aldrich", 0, 20)); // NOI18N
        telefoneLabel.setText("Telefone:");

        servicoTextArea.setBackground(new java.awt.Color(255, 255, 255));
        servicoTextArea.setColumns(20);
        servicoTextArea.setFont(new java.awt.Font("Aldrich", 0, 22)); // NOI18N
        servicoTextArea.setForeground(new java.awt.Color(0, 0, 0));
        servicoTextArea.setRows(5);
        servicoTextArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportView(servicoTextArea);

        descricaoLabel.setFont(new java.awt.Font("Aldrich", 1, 18)); // NOI18N
        descricaoLabel.setText("Serviço:");
        descricaoLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        descricaoLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        registrarBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        registrarBtn.setText("REGISTRAR");
        registrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBtnActionPerformed(evt);
            }
        });

        precoTextField.setBackground(new Color(255,255,255, 165));
        precoTextField.setFont(new java.awt.Font("Aldrich", 0, 22)); // NOI18N
        precoTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        precoLabel.setFont(new java.awt.Font("Aldrich", 0, 20)); // NOI18N
        precoLabel.setText("Preço:");

        telefoneTextField.setBackground(new Color(255,255,255, 165));
        telefoneTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        try {
            telefoneTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        telefoneTextField.setFont(new java.awt.Font("Aldrich", 0, 22)); // NOI18N

        jaPagoGp.add(simRadioBtn);
        simRadioBtn.setFont(new java.awt.Font("Aldrich", 0, 16)); // NOI18N
        simRadioBtn.setText("SIM");
        simRadioBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simRadioBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        simRadioBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        simRadioBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio.png"))); // NOI18N
        simRadioBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        simRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simRadioBtnActionPerformed(evt);
            }
        });

        jaPagoLabel.setFont(new java.awt.Font("Aldrich", 1, 20)); // NOI18N
        jaPagoLabel.setText("Já está pago?");

        jaPagoGp.add(naoRadioBtn);
        naoRadioBtn.setFont(new java.awt.Font("Aldrich", 0, 16)); // NOI18N
        naoRadioBtn.setText("NÃO");
        naoRadioBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        naoRadioBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        naoRadioBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        naoRadioBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio.png"))); // NOI18N
        naoRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naoRadioBtnActionPerformed(evt);
            }
        });

        formaPagPanel.setBackground(new java.awt.Color(37, 86, 255));
        formaPagPanel.setEnabled(false);
        formaPagPanel.setFocusable(false);

        formaPagamentoLabel.setFont(new java.awt.Font("Aldrich", 1, 18)); // NOI18N
        formaPagamentoLabel.setText("Forma de Pagamento:");
        formaPagamentoLabel.setEnabled(false);
        formaPagamentoLabel.setFocusable(false);

        formaPagarGp.add(debitoRadioBtn);
        debitoRadioBtn.setFont(new java.awt.Font("Aldrich", 0, 16)); // NOI18N
        debitoRadioBtn.setText("Débito");
        debitoRadioBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        debitoRadioBtn.setEnabled(false);
        debitoRadioBtn.setFocusable(false);
        debitoRadioBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        debitoRadioBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        debitoRadioBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio.png"))); // NOI18N
        debitoRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debitoRadioBtnActionPerformed(evt);
            }
        });

        formaPagarGp.add(creditoRadioBtn);
        creditoRadioBtn.setFont(new java.awt.Font("Aldrich", 0, 16)); // NOI18N
        creditoRadioBtn.setText("Crédito");
        creditoRadioBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        creditoRadioBtn.setEnabled(false);
        creditoRadioBtn.setFocusable(false);
        creditoRadioBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        creditoRadioBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        creditoRadioBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio.png"))); // NOI18N
        creditoRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditoRadioBtnActionPerformed(evt);
            }
        });

        formaPagarGp.add(dinheiroRadioBtn);
        dinheiroRadioBtn.setFont(new java.awt.Font("Aldrich", 0, 16)); // NOI18N
        dinheiroRadioBtn.setText("Dinheiro");
        dinheiroRadioBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dinheiroRadioBtn.setEnabled(false);
        dinheiroRadioBtn.setFocusable(false);
        dinheiroRadioBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        dinheiroRadioBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        dinheiroRadioBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio.png"))); // NOI18N
        dinheiroRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dinheiroRadioBtnActionPerformed(evt);
            }
        });

        formaPagarGp.add(pixRadioBtn);
        pixRadioBtn.setFont(new java.awt.Font("Aldrich", 0, 16)); // NOI18N
        pixRadioBtn.setText("Pix");
        pixRadioBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pixRadioBtn.setEnabled(false);
        pixRadioBtn.setFocusable(false);
        pixRadioBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        pixRadioBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        pixRadioBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio.png"))); // NOI18N
        pixRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pixRadioBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formaPagPanelLayout = new javax.swing.GroupLayout(formaPagPanel);
        formaPagPanel.setLayout(formaPagPanelLayout);
        formaPagPanelLayout.setHorizontalGroup(
            formaPagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formaPagPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(formaPagamentoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dinheiroRadioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(debitoRadioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creditoRadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pixRadioBtn)
                .addGap(22, 22, 22))
        );
        formaPagPanelLayout.setVerticalGroup(
            formaPagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formaPagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(formaPagamentoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pixRadioBtn)
                .addComponent(debitoRadioBtn)
                .addComponent(creditoRadioBtn)
                .addComponent(dinheiroRadioBtn))
        );

        javax.swing.GroupLayout cadastroPanelLayout = new javax.swing.GroupLayout(cadastroPanel);
        cadastroPanel.setLayout(cadastroPanelLayout);
        cadastroPanelLayout.setHorizontalGroup(
            cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroPanelLayout.createSequentialGroup()
                        .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroPanelLayout.createSequentialGroup()
                                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(telefoneLabel)
                                    .addComponent(telefoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(precoLabel)
                                    .addComponent(precoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroPanelLayout.createSequentialGroup()
                                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastroPanelLayout.createSequentialGroup()
                                        .addComponent(nomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(208, 208, 208))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastroPanelLayout.createSequentialGroup()
                                        .addComponent(descricaoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(192, 192, 192))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastroPanelLayout.createSequentialGroup()
                                        .addComponent(jaPagoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(simRadioBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(naoRadioBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(262, 262, 262)))
                        .addGap(35, 35, 35))
                    .addGroup(cadastroPanelLayout.createSequentialGroup()
                        .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(registrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(35, Short.MAX_VALUE))))
            .addComponent(formaPagPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cadastroPanelLayout.setVerticalGroup(
            cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nomeLabel)
                .addGap(0, 0, 0)
                .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneLabel)
                    .addComponent(precoLabel))
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(precoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(telefoneTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(naoRadioBtn)
                    .addComponent(jaPagoLabel)
                    .addComponent(simRadioBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formaPagPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descricaoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VoltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(cadastroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(VoltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BtnsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cadastroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarBtnActionPerformed
        TelaOS to = new TelaOS();
        to.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarBtnActionPerformed

    private void ExcluirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirBtnActionPerformed
        TelaVendas tv = new TelaVendas();
        tv.setVisible(true);
        dispose();
        JOptionPane.showMessageDialog(null, "Escolha um item para excluir!");
    }//GEN-LAST:event_ExcluirBtnActionPerformed

    private void CadastroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroBtnActionPerformed
        TelaCadastroOS tc = new TelaCadastroOS();
        tc.setVisible(true);
        dispose();
    }//GEN-LAST:event_CadastroBtnActionPerformed

    private void EditarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarBtnActionPerformed
        try {
            TelaOS to = new TelaOS();
            to.setVisible(true);
            dispose();
            JOptionPane.showMessageDialog(null, "Escolha um item para ver os detalhes!");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_EditarBtnActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        TelaInicial ti = new TelaInicial();
        ti.setVisible(true);
        dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void VendasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendasButtonActionPerformed
        TelaVendas tv = new TelaVendas();
        tv.setVisible(true);
        dispose();
    }//GEN-LAST:event_VendasButtonActionPerformed

    private void registrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBtnActionPerformed
        OrdemServico os = new OrdemServico();

        //VARIÁVEIS PARA OS SETS
        String nome = nomeTextField.getText();
        String telefone = telefoneTextField.getText();
        String preco = precoTextField.getText();

        //CAMPOS DE TEXTO
        if (nome.isBlank()) {
            JOptionPane.showMessageDialog(null, "Nome do cliente vazio! Favor inserir para prosseguir!");
        } else {
            os.setNomeCliente(nome);
            if (telefone.isBlank()) {
                JOptionPane.showMessageDialog(null, "Telefone vazio! Favor inserir para prosseguir!");
            } else {
                os.setTelefone(telefone);
                if (preco.isBlank()) {
                    JOptionPane.showMessageDialog(null, "Preço vazio! Favor inserir para prosseguir!");
                } else {
                    if (!OrdemServico.validarPreco(preco)) {
                    } else {
                        preco = preco.replace(",", ".");
                        os.setPreco(Double.parseDouble(preco));

                        DateTimeFormatter form = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
                        os.setDataRecepcao(LocalDateTime.now().format(form));
                        if (!simRadioBtn.isSelected() & !naoRadioBtn.isSelected()) {
                            JOptionPane.showMessageDialog(null, "Favor definir se já foi pago!");
                        } else {
                            if (simRadioBtn.isSelected()) {
                                if (!dinheiroRadioBtn.isSelected() & !debitoRadioBtn.isSelected() & !creditoRadioBtn.isSelected() & !pixRadioBtn.isSelected()) {
                                    JOptionPane.showMessageDialog(null, "Nenhuma forma de pagamento foi definida! Defina uma antes de prosseguir!");
                                } else {
                                    os.setFormaPagamento(formaPagarGp.getSelection().getActionCommand());
                                }
                            }
                            os.setJaPago(jaPagoGp.getSelection().getActionCommand());

                            if (servicoTextArea.getText().isBlank()) {
                                JOptionPane.showMessageDialog(null, "Serviço está vazio! Descreva o que está sendo vendido!");
                            } else {
                                os.setServico(servicoTextArea.getText());

                                if (OsDAO.cadastrarOS(os)) {
                                    JOptionPane.showMessageDialog(null, "O.S registrada com sucesso!");
                                    nomeTextField.setText("");
                                    telefoneTextField.setText("");
                                    servicoTextArea.setText("");
                                    precoTextField.setText("");
                                    formaPagarGp.clearSelection();
                                    jaPagoGp.clearSelection();
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_registrarBtnActionPerformed

    private void OSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OSButtonActionPerformed
        TelaOS tos = new TelaOS();
        tos.setVisible(true);
        dispose();
    }//GEN-LAST:event_OSButtonActionPerformed

    private void simRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simRadioBtnActionPerformed
        simRadioBtn.setActionCommand("Sim");

        if (simRadioBtn.isSelected()) {
            formaPagPanel.setEnabled(true);
            dinheiroRadioBtn.setEnabled(true);
            debitoRadioBtn.setEnabled(true);
            creditoRadioBtn.setEnabled(true);
            pixRadioBtn.setEnabled(true);
            formaPagamentoLabel.setEnabled(true);
        }
    }//GEN-LAST:event_simRadioBtnActionPerformed

    private void naoRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naoRadioBtnActionPerformed
        naoRadioBtn.setActionCommand("Não");

        if (naoRadioBtn.isSelected()) {
            formaPagPanel.setEnabled(false);
            dinheiroRadioBtn.setEnabled(false);
            debitoRadioBtn.setEnabled(false);
            creditoRadioBtn.setEnabled(false);
            pixRadioBtn.setEnabled(false);
            formaPagamentoLabel.setEnabled(false);
            formaPagarGp.clearSelection();
        }
    }//GEN-LAST:event_naoRadioBtnActionPerformed

    private void dinheiroRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dinheiroRadioBtnActionPerformed
        dinheiroRadioBtn.setActionCommand("Dinheiro");
    }//GEN-LAST:event_dinheiroRadioBtnActionPerformed

    private void debitoRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debitoRadioBtnActionPerformed
        debitoRadioBtn.setActionCommand("Débito");
    }//GEN-LAST:event_debitoRadioBtnActionPerformed

    private void creditoRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditoRadioBtnActionPerformed
        creditoRadioBtn.setActionCommand("Crédito");
    }//GEN-LAST:event_creditoRadioBtnActionPerformed

    private void pixRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pixRadioBtnActionPerformed
        pixRadioBtn.setActionCommand("Pix");
    }//GEN-LAST:event_pixRadioBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroOS.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroOS.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroOS.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroOS.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroOS().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnsPanel;
    private javax.swing.JButton CadastroBtn;
    private javax.swing.JButton EditarBtn;
    private javax.swing.JButton ExcluirBtn;
    private javax.swing.JButton OSButton;
    private javax.swing.JButton VendasButton;
    private javax.swing.JButton VoltarBtn;
    private javax.swing.JPanel cadastroPanel;
    private javax.swing.JRadioButton creditoRadioBtn;
    private javax.swing.JRadioButton debitoRadioBtn;
    private javax.swing.JLabel descricaoLabel;
    private javax.swing.JRadioButton dinheiroRadioBtn;
    private javax.swing.JPanel formaPagPanel;
    private javax.swing.JLabel formaPagamentoLabel;
    private javax.swing.ButtonGroup formaPagarGp;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup jaPagoGp;
    private javax.swing.JLabel jaPagoLabel;
    private javax.swing.JRadioButton naoRadioBtn;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JRadioButton pixRadioBtn;
    private javax.swing.JLabel precoLabel;
    private javax.swing.JTextField precoTextField;
    private javax.swing.JButton registrarBtn;
    private javax.swing.JTextArea servicoTextArea;
    private javax.swing.JRadioButton simRadioBtn;
    private javax.swing.JLabel telefoneLabel;
    private javax.swing.JFormattedTextField telefoneTextField;
    // End of variables declaration//GEN-END:variables
}
