/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p.i.fame;

import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.VendaDAO;
import model.Venda;

/**
 *
 * @author User
 */
public class TelaCadastroVenda extends javax.swing.JFrame {

    /**
     * Creates new form TelaVendas
     */
    public TelaCadastroVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formaPagarGp = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        BtnsPanel = new javax.swing.JPanel();
        CadastroBtn = new javax.swing.JButton();
        EditarBtn = new javax.swing.JButton();
        ExcluirBtn = new javax.swing.JButton();
        VoltarBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        VendasButton = new javax.swing.JButton();
        OSButton = new javax.swing.JButton();
        cadastroPanel = new javax.swing.JPanel();
        relogioRadioBtn = new javax.swing.JRadioButton();
        acosRadioBtn = new javax.swing.JRadioButton();
        pulseiraRadioBtn = new javax.swing.JRadioButton();
        pilhaRadioBtn = new javax.swing.JRadioButton();
        despertadoresRadioBtn = new javax.swing.JRadioButton();
        precoTextField = new javax.swing.JTextField();
        precoLabel = new javax.swing.JLabel();
        descontoTextField = new javax.swing.JTextField();
        descontoLabel = new javax.swing.JLabel();
        formaPagamentoLabel = new javax.swing.JLabel();
        debitoRadioBtn = new javax.swing.JRadioButton();
        creditoRadioBtn = new javax.swing.JRadioButton();
        dinheiroRadioBtn = new javax.swing.JRadioButton();
        pixRadioBtn = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaoTextArea = new javax.swing.JTextArea();
        descricaoLabel = new javax.swing.JLabel();
        registrarBtn = new javax.swing.JButton();
        produtosLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        BtnsPanel.setBackground(new Color(255,255,0,96));

        CadastroBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        CadastroBtn.setLabel("<html><center>Registrar<br>Venda</center></html>");
        CadastroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroBtnActionPerformed(evt);
            }
        });

        EditarBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        EditarBtn.setText("<html><center>Detalhe<br>Venda</center></html>");
        EditarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarBtnActionPerformed(evt);
            }
        });

        ExcluirBtn.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        ExcluirBtn.setText("<html><center>Excluir<br>Venda</center></html>");
        ExcluirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BtnsPanelLayout = new javax.swing.GroupLayout(BtnsPanel);
        BtnsPanel.setLayout(BtnsPanelLayout);
        BtnsPanelLayout.setHorizontalGroup(
            BtnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnsPanelLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(CadastroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(EditarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(ExcluirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        BtnsPanelLayout.setVerticalGroup(
            BtnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BtnsPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(BtnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadastroBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExcluirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        VoltarBtn.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        VoltarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        VoltarBtn.setBorder(null);
        VoltarBtn.setContentAreaFilled(false);
        VoltarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VoltarBtn.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        VoltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarBtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(37, 86, 255));

        homeButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setText("⌂");
        homeButton.setBorderPainted(false);
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        VendasButton.setBackground(new java.awt.Color(0, 0, 0));
        VendasButton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        VendasButton.setForeground(new java.awt.Color(255, 255, 255));
        VendasButton.setText("VENDAS");
        VendasButton.setBorder(null);
        VendasButton.setBorderPainted(false);
        VendasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendasButtonActionPerformed(evt);
            }
        });

        OSButton.setBackground(new java.awt.Color(255, 255, 255));
        OSButton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        OSButton.setForeground(new java.awt.Color(0, 0, 0));
        OSButton.setBorder(null);
        OSButton.setLabel("<html><center>ORDEM<br>SERVIÇO</center></html>");
        OSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OSButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VendasButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(OSButton, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeButton)
                .addGap(178, 178, 178)
                .addComponent(VendasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {OSButton, VendasButton});

        cadastroPanel.setBackground(new java.awt.Color(37, 86, 255));

        relogioRadioBtn.setFont(new java.awt.Font("Aldrich", 0, 20)); // NOI18N
        relogioRadioBtn.setForeground(new Color(255, 255, 255, 127));
        relogioRadioBtn.setText("Relógio");
        relogioRadioBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        relogioRadioBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        relogioRadioBtn.setIconTextGap(7);
        relogioRadioBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        relogioRadioBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio.png"))); // NOI18N

        acosRadioBtn.setFont(new java.awt.Font("Aldrich", 0, 20)); // NOI18N
        acosRadioBtn.setForeground(new Color(255, 255, 255, 127));
        acosRadioBtn.setText("Aços");
        acosRadioBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acosRadioBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        acosRadioBtn.setIconTextGap(7);
        acosRadioBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        acosRadioBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio.png"))); // NOI18N

        pulseiraRadioBtn.setFont(new java.awt.Font("Aldrich", 0, 20)); // NOI18N
        pulseiraRadioBtn.setForeground(new Color(255, 255, 255, 127));
        pulseiraRadioBtn.setText("Pulseira");
        pulseiraRadioBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pulseiraRadioBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        pulseiraRadioBtn.setIconTextGap(7);
        pulseiraRadioBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        pulseiraRadioBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio.png"))); // NOI18N

        pilhaRadioBtn.setFont(new java.awt.Font("Aldrich", 0, 20)); // NOI18N
        pilhaRadioBtn.setForeground(new Color(255, 255, 255, 127));
        pilhaRadioBtn.setText("Pilha");
        pilhaRadioBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pilhaRadioBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        pilhaRadioBtn.setIconTextGap(7);
        pilhaRadioBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        pilhaRadioBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio.png"))); // NOI18N

        despertadoresRadioBtn.setFont(new java.awt.Font("Aldrich", 0, 20)); // NOI18N
        despertadoresRadioBtn.setForeground(new Color(255, 255, 255, 127));
        despertadoresRadioBtn.setText("Despertadores");
        despertadoresRadioBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        despertadoresRadioBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        despertadoresRadioBtn.setIconTextGap(7);
        despertadoresRadioBtn.setMargin(new java.awt.Insets(2, 0, 2, 0));
        despertadoresRadioBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        despertadoresRadioBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio.png"))); // NOI18N

        precoTextField.setBackground(new Color(255,255,255, 165));
        precoTextField.setFont(new java.awt.Font("Aldrich", 0, 24)); // NOI18N
        precoTextField.setForeground(new java.awt.Color(0, 0, 0));
        precoTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        precoLabel.setFont(new java.awt.Font("Aldrich", 0, 22)); // NOI18N
        precoLabel.setForeground(new Color(255, 255, 255, 90));
        precoLabel.setText("Preço:");

        descontoTextField.setBackground(new Color(255,255,255, 165));
        descontoTextField.setFont(new java.awt.Font("Aldrich", 0, 24)); // NOI18N
        descontoTextField.setForeground(new java.awt.Color(0, 0, 0));
        descontoTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        descontoLabel.setFont(new java.awt.Font("Aldrich", 0, 22)); // NOI18N
        descontoLabel.setForeground(new Color(255, 255, 255, 90));
        descontoLabel.setText("Desconto:");

        formaPagamentoLabel.setFont(new java.awt.Font("Aldrich", 0, 24)); // NOI18N
        formaPagamentoLabel.setForeground(new Color(255,255,255, 127));
        formaPagamentoLabel.setText("Forma de Pagamento:");

        formaPagarGp.add(debitoRadioBtn);
        debitoRadioBtn.setFont(new java.awt.Font("Aldrich", 0, 20)); // NOI18N
        debitoRadioBtn.setForeground(new Color(255,255,255, 127));
        debitoRadioBtn.setText("Débito");
        debitoRadioBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        debitoRadioBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        debitoRadioBtn.setIconTextGap(7);
        debitoRadioBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        debitoRadioBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio.png"))); // NOI18N
        debitoRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debitoRadioBtnActionPerformed(evt);
            }
        });

        formaPagarGp.add(creditoRadioBtn);
        creditoRadioBtn.setFont(new java.awt.Font("Aldrich", 0, 20)); // NOI18N
        creditoRadioBtn.setForeground(new Color(255,255,255, 127));
        creditoRadioBtn.setText("Crédito");
        creditoRadioBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        creditoRadioBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        creditoRadioBtn.setIconTextGap(7);
        creditoRadioBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        creditoRadioBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio.png"))); // NOI18N
        creditoRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditoRadioBtnActionPerformed(evt);
            }
        });

        formaPagarGp.add(dinheiroRadioBtn);
        dinheiroRadioBtn.setFont(new java.awt.Font("Aldrich", 0, 20)); // NOI18N
        dinheiroRadioBtn.setForeground(new Color(255,255,255, 127));
        dinheiroRadioBtn.setText("Dinheiro");
        dinheiroRadioBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dinheiroRadioBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        dinheiroRadioBtn.setIconTextGap(7);
        dinheiroRadioBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        dinheiroRadioBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio.png"))); // NOI18N
        dinheiroRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dinheiroRadioBtnActionPerformed(evt);
            }
        });

        formaPagarGp.add(pixRadioBtn);
        pixRadioBtn.setFont(new java.awt.Font("Aldrich", 0, 20)); // NOI18N
        pixRadioBtn.setForeground(new Color(255,255,255, 127));
        pixRadioBtn.setText("Pix");
        pixRadioBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pixRadioBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        pixRadioBtn.setIconTextGap(7);
        pixRadioBtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio-button.png"))); // NOI18N
        pixRadioBtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio.png"))); // NOI18N
        pixRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pixRadioBtnActionPerformed(evt);
            }
        });

        descricaoTextArea.setBackground(new java.awt.Color(255, 255, 255));
        descricaoTextArea.setColumns(20);
        descricaoTextArea.setFont(new java.awt.Font("Aldrich", 0, 24)); // NOI18N
        descricaoTextArea.setForeground(new java.awt.Color(0, 0, 0));
        descricaoTextArea.setRows(5);
        descricaoTextArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jScrollPane1.setViewportView(descricaoTextArea);

        descricaoLabel.setFont(new java.awt.Font("Aldrich", 0, 20)); // NOI18N
        descricaoLabel.setForeground(new Color(255,255,255, 127));
        descricaoLabel.setText("Descrição:");
        descricaoLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        registrarBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        registrarBtn.setText("REGISTRAR");
        registrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarBtnActionPerformed(evt);
            }
        });

        produtosLabel.setFont(new java.awt.Font("Aldrich", 1, 30)); // NOI18N
        produtosLabel.setForeground(new Color(255, 255, 255, 127));
        produtosLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        produtosLabel.setText("PRODUTOS");

        javax.swing.GroupLayout cadastroPanelLayout = new javax.swing.GroupLayout(cadastroPanel);
        cadastroPanel.setLayout(cadastroPanelLayout);
        cadastroPanelLayout.setHorizontalGroup(
            cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(produtosLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(cadastroPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(cadastroPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(registrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastroPanelLayout.createSequentialGroup()
                        .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(precoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precoLabel))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descontoLabel)
                            .addComponent(descontoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descricaoLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastroPanelLayout.createSequentialGroup()
                        .addComponent(formaPagamentoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dinheiroRadioBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(debitoRadioBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(creditoRadioBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pixRadioBtn)))
                .addGap(25, 25, 25))
            .addGroup(cadastroPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(relogioRadioBtn)
                .addGap(18, 18, 18)
                .addComponent(pilhaRadioBtn)
                .addGap(18, 18, 18)
                .addComponent(acosRadioBtn)
                .addGap(18, 18, 18)
                .addComponent(pulseiraRadioBtn)
                .addGap(18, 18, 18)
                .addComponent(despertadoresRadioBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(63, 63, 63))
        );

        cadastroPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {descontoTextField, precoTextField});

        cadastroPanelLayout.setVerticalGroup(
            cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(produtosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(relogioRadioBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(acosRadioBtn)
                        .addComponent(pulseiraRadioBtn)
                        .addComponent(despertadoresRadioBtn)
                        .addComponent(pilhaRadioBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descontoLabel)
                    .addComponent(precoLabel))
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descontoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formaPagamentoLabel)
                    .addComponent(debitoRadioBtn)
                    .addComponent(creditoRadioBtn)
                    .addComponent(dinheiroRadioBtn)
                    .addComponent(pixRadioBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descricaoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VoltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadastroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(VoltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(BtnsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cadastroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarBtnActionPerformed
        TelaVendas tv = new TelaVendas();
        tv.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarBtnActionPerformed

    private void ExcluirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirBtnActionPerformed
        TelaVendas tv = new TelaVendas();
        tv.setVisible(true);
        dispose();
        JOptionPane.showMessageDialog(null, "Escolha um item para excluir!");
    }//GEN-LAST:event_ExcluirBtnActionPerformed

    private void CadastroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroBtnActionPerformed
        TelaCadastroVenda tc = new TelaCadastroVenda();
        tc.setVisible(true);
        dispose();
    }//GEN-LAST:event_CadastroBtnActionPerformed

    private void EditarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarBtnActionPerformed
        TelaVendas tv = new TelaVendas();
        tv.setVisible(true);
        dispose();
        JOptionPane.showMessageDialog(null, "Escolha um item para ver os detalhes!");
    }//GEN-LAST:event_EditarBtnActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        TelaInicial ti = new TelaInicial();
        ti.setVisible(true);
        dispose();
    }//GEN-LAST:event_homeButtonActionPerformed

    private void VendasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendasButtonActionPerformed
        TelaVendas tv = new TelaVendas();
        tv.setVisible(true);
        dispose();
    }//GEN-LAST:event_VendasButtonActionPerformed

    private void debitoRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debitoRadioBtnActionPerformed
        debitoRadioBtn.setActionCommand("Débito");
    }//GEN-LAST:event_debitoRadioBtnActionPerformed

    private void creditoRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditoRadioBtnActionPerformed
        creditoRadioBtn.setActionCommand("Crédito");
    }//GEN-LAST:event_creditoRadioBtnActionPerformed

    private void dinheiroRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dinheiroRadioBtnActionPerformed
        dinheiroRadioBtn.setActionCommand("Dinheiro");
    }//GEN-LAST:event_dinheiroRadioBtnActionPerformed

    private void pixRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pixRadioBtnActionPerformed
        pixRadioBtn.setActionCommand("Pix");
    }//GEN-LAST:event_pixRadioBtnActionPerformed

    private void registrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarBtnActionPerformed
        Venda v = new Venda();

        //PRODUTOS
        ArrayList<String> produtos = new ArrayList<>();
        if (!relogioRadioBtn.isSelected() & !pilhaRadioBtn.isSelected() & !acosRadioBtn.isSelected() & !pulseiraRadioBtn.isSelected() & !despertadoresRadioBtn.isSelected()) {
            JOptionPane.showMessageDialog(null, "Não há produtos selecionados! Favor selecionar os produtos que estão sendo vendidos!");
        } else {
            if (relogioRadioBtn.isSelected()) {
                produtos.add(relogioRadioBtn.getText());
            }
            if (pilhaRadioBtn.isSelected()) {
                produtos.add(pilhaRadioBtn.getText());
            }
            if (acosRadioBtn.isSelected()) {
                produtos.add(acosRadioBtn.getText());
            }
            if (pulseiraRadioBtn.isSelected()) {
                produtos.add(pulseiraRadioBtn.getText());
            }
            if (despertadoresRadioBtn.isSelected()) {
                produtos.add(despertadoresRadioBtn.getText());
            }

            String produtosV = String.join(", ", produtos);
            v.setProdutos(produtosV);

            //VARIÁVEIS PARA OS SETS
            String preco = precoTextField.getText();
            String desconto = descontoTextField.getText();

            //CAMPOS DE TEXTO
            if (preco.isBlank()) {
                JOptionPane.showMessageDialog(null, "Preço não definido! Favor definir o valor da venda para prosseguir!");
            } else {
                if (!Venda.validarPreco(preco)) {
                } else {
                    preco = preco.replace(",", ".");
                    v.setValorTotal(Double.parseDouble(preco));

                    if (!Venda.validarDesconto(desconto)) {
                    } else {
                        if (desconto.isBlank()) {
                            desconto = "0";
                        }
                        desconto = desconto.replace(",", "");
                        v.setDesconto(Double.parseDouble(desconto));

                        DateTimeFormatter form = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
                        v.setData(LocalDateTime.now().format(form));
                        if (!dinheiroRadioBtn.isSelected() & !debitoRadioBtn.isSelected() & !creditoRadioBtn.isSelected() & !pixRadioBtn.isSelected()) {
                            JOptionPane.showMessageDialog(null, "Nenhuma forma de pagamento foi definida! Defina uma antes de prosseguir!");
                        } else {
                            v.setFormaPagamento(formaPagarGp.getSelection().getActionCommand());

                            if (descricaoTextArea.getText().isBlank()) {
                                JOptionPane.showMessageDialog(null, "Descrição está vazia! Descreva o que está sendo vendido!");
                            } else {
                                v.setDescricao(descricaoTextArea.getText());

                                if (VendaDAO.cadastrarVenda(v)) {
                                    JOptionPane.showMessageDialog(null, "Venda registrada com sucesso!");
                                    relogioRadioBtn.setSelected(false);
                                    pilhaRadioBtn.setSelected(false);
                                    acosRadioBtn.setSelected(false);
                                    pulseiraRadioBtn.setSelected(false);
                                    despertadoresRadioBtn.setSelected(false);
                                    precoTextField.setText("");
                                    descontoTextField.setText("");
                                    descricaoTextArea.setText("");
                                    formaPagarGp.clearSelection();
                                }
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_registrarBtnActionPerformed

    private void OSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OSButtonActionPerformed
        TelaOS tos = new TelaOS();
        tos.setVisible(true);
        dispose();
    }//GEN-LAST:event_OSButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroVenda().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnsPanel;
    private javax.swing.JButton CadastroBtn;
    private javax.swing.JButton EditarBtn;
    private javax.swing.JButton ExcluirBtn;
    private javax.swing.JButton OSButton;
    private javax.swing.JButton VendasButton;
    private javax.swing.JButton VoltarBtn;
    private javax.swing.JRadioButton acosRadioBtn;
    private javax.swing.JPanel cadastroPanel;
    private javax.swing.JRadioButton creditoRadioBtn;
    private javax.swing.JRadioButton debitoRadioBtn;
    private javax.swing.JLabel descontoLabel;
    private javax.swing.JTextField descontoTextField;
    private javax.swing.JLabel descricaoLabel;
    private javax.swing.JTextArea descricaoTextArea;
    private javax.swing.JRadioButton despertadoresRadioBtn;
    private javax.swing.JRadioButton dinheiroRadioBtn;
    private javax.swing.JLabel formaPagamentoLabel;
    private javax.swing.ButtonGroup formaPagarGp;
    private javax.swing.JButton homeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton pilhaRadioBtn;
    private javax.swing.JRadioButton pixRadioBtn;
    private javax.swing.JLabel precoLabel;
    private javax.swing.JTextField precoTextField;
    private javax.swing.JLabel produtosLabel;
    private javax.swing.JRadioButton pulseiraRadioBtn;
    private javax.swing.JButton registrarBtn;
    private javax.swing.JRadioButton relogioRadioBtn;
    // End of variables declaration//GEN-END:variables
}
